version: '2.0'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 35569:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_kullanici_adi
      WORDPRESS_DB_PASSWORD: db-kullanici_sifresi
      WORDPRESS_DB_NAME: database_ismi
      MYSQL_ROOT_PASSWORD: mysqlpassw0rd1
    volumes:
      - ./wordpress:/var/www/html
        
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: database_ismi
      MYSQL_USER: db_kullanici_adi
      MYSQL_PASSWORD: db_kullanici_sifresi
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
